FROM golang:1.19.5-alpine AS Builder
WORKDIR /build/
COPY ./ ./
RUN go mod download && \
  CGO_ENABLED=0 GOOS=linux go build -o echo

FROM scratch
WORKDIR /root/
COPY --from=builder /build/echo ./
EXPOSE 1323
CMD ["./echo"]
